export interface PhotographicPreset {
    id: number;
    name: string;
    era: string;
    photoType: string;
    cameraType: string;
    filmOrMedia: string;
    visualStyle: string;
}

type PresetTuple = [number, string, string, string, string, string, string];

const PRESETS: PresetTuple[] = [
    [1,'1950s','1950s Family Snapshot','Casual family snapshot','Kodak Brownie box camera','Black-and-white 120 film','Soft focus, low contrast, visible film grain, slightly faded edges'],
    [2,'1950s','1950s Street Documentary','Street documentary','Leica IIIc rangefinder','35mm black-and-white film','Strong grain, deep shadows, scratched emulsion, candid composition'],
    [3,'1950s','1950s Wedding Photograph','Wedding portrait','Large-format Graflex camera','Black-and-white sheet film','Formal framing, soft highlights, studio flash, slightly retouched skin'],
    [4,'1950s','1950s Newspaper Photo','Press photograph','Speed Graphic','Black-and-white 4x5 film','Hard flash, high contrast, rough halftone texture, imperfect focus'],
    [5,'1950s','1950s Vacation Slide','Holiday snapshot','Argus C3','Kodachrome color slide film','Warm colors, moderate saturation, slight color fading, rounded contrast'],
    [6,'1950s','1950s School Portrait','School portrait','Studio large-format camera','Black-and-white portrait film','Neutral backdrop, centered pose, gentle lighting, formal expression'],
    [7,'1950s','1950s Carnival Photo','Carnival snapshot','Brownie Hawkeye Flash','120 color film','Direct flash, soft details, muted colors, visible dust marks'],
    [8,'1950s','1950s Sports Action','Sports action photograph','Nikon S2 rangefinder','High-speed black-and-white 35mm film','Motion blur, high contrast, grainy shadows, slightly underexposed'],
    [9,'1950s','1950s Newspaper Portrait','Editorial portrait','Rolleiflex TLR','Medium-format black-and-white film','Sharp central subject, soft background, printed-paper texture'],
    [10,'1950s','1950s Home Party','Indoor party snapshot','Kodak Brownie Flash camera','Black-and-white 120 film','Harsh flash, dark background, uneven exposure, authentic grain'],
    [11,'1960s','1960s Beatnik Street Photo','Urban street photograph','Leica M3','Tri-X black-and-white 35mm film','High contrast, gritty grain, candid framing, deep blacks'],
    [12,'1960s','1960s Civil Rights March','Historic crowd documentary','Nikon F SLR','Black-and-white 35mm film','Documentary realism, visible grain, imperfect framing, natural light'],
    [13,'1960s','1960s Rock Concert','Concert photograph','Pentax Spotmatic','Color negative 35mm film','Colored stage lights, motion blur, heavy grain, warm color cast'],
    [14,'1960s','1960s Summer of Love','Counterculture street portrait','Minolta SRT-101','Kodachrome 35mm film','Warm saturated colors, sun flare, soft focus, psychedelic atmosphere'],
    [15,'1960s','1960s Olympic Stadium','Sports spectator photograph','Canonflex SLR','Color slide film','Bright daylight, vivid uniforms, moderate grain, slightly faded colors'],
    [16,'1960s','1960s Mod Fashion','Fashion street portrait','Yashica Electro 35','Color negative film','Clean composition, pastel colors, soft contrast, mild lens flare'],
    [17,'1960s','1960s Newspaper Flash','Press event photograph','Nikon F with flash','Black-and-white 35mm film','Direct flash, sharp faces, hard shadows, tabloid realism'],
    [18,'1960s','1960s Beach Snapshot','Beach vacation snapshot','Kodak Instamatic 100','126 cartridge color film','Square framing, washed colors, soft focus, heavy vignette'],
    [19,'1960s','1960s Family Picnic','Family picnic photograph','Olympus Pen half-frame camera','35mm color negative film','Small-frame softness, warm sunlight, natural poses, faded colors'],
    [20,'1960s','1960s Moon Landing Reaction','Living-room documentary','Polaroid Land Camera','Instant film','Low-resolution instant texture, greenish indoor tones, thick white border'],
    [21,'1970s','1970s Woodstock Crowd','Music festival documentary','Nikon F2','Kodak Tri-X 35mm film','Heavy grain, muddy shadows, overcast light, spontaneous framing'],
    [22,'1970s','1970s Polaroid Party','House party snapshot','Polaroid SX-70','Integral instant film','Soft focus, warm color shift, white frame, chemical imperfections'],
    [23,'1970s','1970s Disco Dancefloor','Nightlife photograph','Canon AE-1','Color negative 35mm film','Colored lights, motion blur, orange skin tones, visible grain'],
    [24,'1970s','1970s Sports Magazine','Sports action photograph','Canon F-1 with telephoto lens','High-speed color film','Strong motion blur, saturated colors, rough focus, editorial crop'],
    [25,'1970s','1970s Road Trip','Road-trip snapshot','Minolta SRT-200','Kodacolor 35mm film','Warm faded colors, sun flare, dusty atmosphere, casual framing'],
    [26,'1970s','1970s Family Vacation','Tourist snapshot','Kodak Instamatic 104','126 color cartridge film','Soft square image, faded reds, bright flash, slight vignette'],
    [27,'1970s','1970s Punk Club','Underground music photograph','Olympus OM-1','Black-and-white 35mm film','Harsh flash, strong grain, tilted composition, dirty club atmosphere'],
    [28,'1970s','1970s Olympic Ceremony','Olympic spectator photograph','Pentax K1000','Color slide film','Bright daylight, crisp uniforms, moderate grain, vintage color cast'],
    [29,'1970s','1970s Studio Portrait','Portrait studio photograph','Hasselblad 500C','120 color negative film','Medium-format detail, warm skin tones, soft studio light, muted colors'],
    [30,'1970s','1970s Birthday Flash','Birthday snapshot','Polaroid Big Shot','Instant film','Direct flash, red-eye, soft edges, warm yellowish color shift'],
    [31,'1980s','1980s Mall Snapshot','Shopping mall photograph','Canon Sure Shot','Color negative 35mm film','On-camera flash, slight red-eye, saturated colors, casual framing'],
    [32,'1980s','1980s Polaroid Portrait','Casual portrait','Polaroid Sun 660','600 instant film','Soft focus, pale highlights, white border, faded pastel colors'],
    [33,'1980s','1980s Skateboard Photo','Action sports photograph','Nikon FM2','High-speed 35mm film','Frozen action, hard flash, strong grain, slightly cool shadows'],
    [34,'1980s','1980s Nightclub Flash','Nightclub snapshot','Yashica T4','Color negative film','Direct flash, dark background, red-eye, neon color casts'],
    [35,'1980s','1980s Family Camcorder Still','Home-video frame','VHS camcorder','Analog videotape frame','Low resolution, interlacing lines, washed colors, timestamp overlay'],
    [36,'1980s','1980s Olympic Crowd','Sports event photograph','Canon T70','Color slide film','Bright colors, moderate sharpness, slight film grain, telephoto compression'],
    [37,'1980s','1980s Music Video Look','Stylized music portrait','35mm SLR with zoom lens','Color negative 35mm film','Strong backlight, colored gels, soft diffusion, high saturation'],
    [38,'1980s','1980s Roadside Diner','Travel snapshot','Minolta X-700','Kodak Gold 35mm film','Warm colors, slight grain, flash reflections, nostalgic composition'],
    [39,'1980s','1980s Wedding Reception','Wedding party photograph','Nikon F3','Color negative film','Direct flash, warm indoor tones, red-eye, slightly overexposed highlights'],
    [40,'1980s','1980s Newsstand Photo','Urban editorial photograph','Leica M6','Black-and-white 35mm film','Fine grain, high contrast, candid street composition, newspaper realism'],
    [41,'1990s','1990s Disposable Camera','Casual snapshot','Fujifilm QuickSnap','Disposable-camera 35mm film','Strong flash, soft focus, uneven exposure, heavy consumer-film grain'],
    [42,'1990s','1990s Rave Photograph','Nightlife documentary','Canon EOS 500','Color negative 35mm film','Flash-lit faces, motion blur, neon colors, dark surroundings'],
    [43,'1990s','1990s Grunge Concert','Concert photograph','Nikon F90','High-speed color film','Heavy grain, underexposure, smoky atmosphere, blurred movement'],
    [44,'1990s','1990s Olympic Spectator','Sports crowd photograph','Canon EOS-1','Professional 35mm color film','Sharp telephoto look, vivid colors, moderate grain, compressed background'],
    [45,'1990s','1990s Mall Portrait','Teen portrait','Automatic compact camera','Consumer color negative film','Direct flash, red-eye, cool shadows, casual centered framing'],
    [46,'1990s','1990s Skatepark Photo','Skateboarding action photograph','Canon EOS Rebel','35mm color negative film','Wide-angle distortion, flash freeze, saturated clothes, visible grain'],
    [47,'1990s','1990s House Party','Party snapshot','Olympus mju-II','35mm color film','Strong built-in flash, dark corners, red-eye, spontaneous expressions'],
    [48,'1990s','1990s Travel Postcard','Tourist photograph','Minolta Dynax 500si','Color slide film','Bright saturated colors, sharp daylight, moderate grain, postcard framing'],
    [49,'1990s','1990s Family Camcorder','Home-video frame','Hi8 camcorder','Hi8 videotape frame','Low resolution, analog noise, timestamp, warm indoor colors'],
    [50,'1990s','1990s Studio Fashion','Fashion editorial','Mamiya RZ67','120 color negative film','Medium-format clarity, muted colors, soft flash, editorial composition'],
    [51,'2000s','2000s Point-and-Shoot','Casual snapshot','Canon PowerShot compact camera','Early digital CCD image','Low-resolution digital noise, harsh flash, cool white balance'],
    [52,'2000s','2000s MySpace Portrait','Self-portrait','Compact digital camera','Early digital JPEG','Flash reflection, mirror pose, low resolution, oversaturated colors'],
    [53,'2000s','2000s Club Photograph','Nightclub snapshot','Sony Cyber-shot','Digital CCD sensor','Harsh flash, red-eye, deep black background, motion blur'],
    [54,'2000s','2000s Festival Photo','Music festival photograph','Canon EOS 20D','Early DSLR digital image','Moderate digital noise, strong sunlight, realistic colors, candid framing'],
    [55,'2000s','2000s Olympic Stadium','Sports spectator photograph','Nikon D70 DSLR','Early DSLR image','Sharp digital detail, slightly cool tones, moderate noise, telephoto look'],
    [56,'2000s','2000s Birthday Flash','Birthday party snapshot','Kodak EasyShare','Consumer digital camera','Strong flash, pale skin tones, slight blur, compact-camera realism'],
    [57,'2000s','2000s Road Trip','Travel photograph','Fujifilm FinePix','Digital JPEG','Bright colors, slightly compressed detail, blue sky, casual composition'],
    [58,'2000s','2000s Skate Video Frame','Action-video still','MiniDV camcorder','MiniDV digital video frame','Interlacing artifacts, motion blur, low dynamic range, timestamp'],
    [59,'2000s','2000s Red Carpet','Celebrity event photograph','Professional DSLR with flash','Early digital RAW image','Direct flash, sharp faces, glossy highlights, slightly cool skin tones'],
    [60,'2000s','2000s Street Documentary','Urban documentary','Canon EOS 5D','Full-frame digital image','Natural light, restrained colors, realistic detail, subtle digital noise'],
    [61,'1950s','1950s Formal Family Portrait','Formal family portrait','Rolleiflex TLR','120 black-and-white film','Centered composition, soft shadows, controlled studio lighting'],
    [62,'1950s','1950s Train Station','Travel documentary','Leica IIIf','Black-and-white 35mm film','Fine grain, atmospheric haze, candid movement, slightly underexposed'],
    [63,'1960s','1960s Protest Portrait','Documentary portrait','Nikon F','Tri-X black-and-white film','Crisp faces, gritty grain, high contrast, authentic newspaper look'],
    [64,'1960s','1960s Drive-In Cinema','Drive-in snapshot','Kodak Instamatic','126 color film','Flash-lit interior, faded colors, soft focus, nostalgic framing'],
    [65,'1970s','1970s Football Supporter','Sports crowd photograph','Pentax Spotmatic','Color negative 35mm film','Warm grain, imperfect focus, crowded background, natural daylight'],
    [66,'1970s','1970s Carnival Parade','Street festival photograph','Olympus OM-1','Color slide film','Bright colors, slight overexposure, motion blur, vintage saturation'],
    [67,'1970s','1970s Office Snapshot','Workplace documentary','Kodak Instamatic','126 color film','Warm fluorescent light, soft details, square crop, faded colors'],
    [68,'1980s','1980s Aerobics Class','Lifestyle photograph','Nikon FG','Color negative 35mm film','Bright colors, on-camera flash, slight grain, energetic composition'],
    [69,'1980s','1980s Concert Backstage','Backstage documentary','Leica M6','Black-and-white 35mm film','Available light, deep shadows, fine grain, intimate candid feeling'],
    [70,'1980s','1980s Street Parade','Public celebration photograph','Canon AE-1 Program','Color negative film','Warm skin tones, slight haze, casual framing, moderate grain'],
    [71,'1990s','1990s School Trip','Student group photograph','Disposable 35mm camera','Consumer color film','Harsh flash, soft corners, washed colors, imperfect composition'],
    [72,'1990s','1990s Sports Bar','Fan snapshot','Compact autofocus camera','Color negative film','Direct flash, dark room, red-eye, warm yellow lighting'],
    [73,'1990s','1990s Parade Crowd','Street celebration photograph','Canon EOS 300','35mm color negative film','Moderate grain, bright colors, candid expressions, documentary framing'],
    [74,'1990s','1990s Teen Bedroom','Personal snapshot','Polaroid 600','Instant film','Soft focus, pale colors, white border, spontaneous pose'],
    [75,'1990s','1990s Beach Party','Beach party photograph','Waterproof disposable camera','35mm color film','Strong sunlight, cyan shadows, soft details, saturated swimwear'],
    [76,'1990s','1990s Fashion Editorial','Magazine fashion photograph','Hasselblad 500CM','120 color negative film','Clean medium-format detail, muted palette, soft directional lighting'],
    [77,'1990s','1990s City Night','Night street photograph','Nikon F4','High-speed color film','Neon reflections, visible grain, slight motion blur, cool shadows'],
    [78,'1990s','1990s Family Reunion','Group family photograph','Minolta Maxxum','Color negative 35mm film','Built-in flash, casual smiles, warm colors, slightly soft focus'],
    [79,'2000s','2000s Dorm Room Snapshot','Indoor lifestyle photograph','Sony Cyber-shot DSC-P series','Early digital JPEG','Harsh flash, low resolution, cool white balance, visible compression'],
    [80,'2000s','2000s Street Festival','Public event photograph','Canon EOS 350D','Early DSLR image','Natural daylight, moderate digital noise, realistic color, candid framing'],
    [81,'1950s','1950s Newsreel Frame','Newsreel still','35mm motion-picture camera','Black-and-white cinema film','High contrast, visible scratches, cinematic grain, documentary framing'],
    [82,'1960s','1960s Cinema Lobby Photo','Movie-theater snapshot','Kodak Instamatic','126 color film','Soft square image, flash glare, faded reds, casual tourist feel'],
    [83,'1970s','1970s Flea Market','Street market photograph','Yashica Electro 35','Color negative 35mm film','Warm tones, mild grain, natural shadows, slightly faded colors'],
    [84,'1970s','1970s Protest Crowd','Crowd documentary','Nikon F2','Black-and-white 35mm film','Strong grain, high contrast, imperfect framing, authentic press style'],
    [85,'1980s','1980s Family Vacation','Tourist snapshot','Kodak Disc camera','Disc color film','Small image area, soft detail, bright flash, faded consumer colors'],
    [86,'1980s','1980s Arcade Photo','Arcade snapshot','Polaroid 660','600 instant film','Flash-lit faces, dark background, soft focus, chemical color shift'],
    [87,'1980s','1980s School Dance','School event photograph','Canon Sure Shot','Color negative 35mm film','Direct flash, red-eye, colored lights, spontaneous movement'],
    [88,'1990s','1990s Record Store','Lifestyle street photograph','Leica M6','Black-and-white 35mm film','Fine grain, soft window light, candid pose, documentary realism'],
    [89,'1990s','1990s Comic Convention','Fan event photograph','Canon EOS 50E','Color negative 35mm film','Indoor flash, warm skin tones, moderate grain, crowded background'],
    [90,'2000s','2000s Graduation Photo','Graduation photograph','Nikon D50 DSLR','Early digital image','Sharp faces, slight digital noise, bright daylight, realistic colors'],
    [91,'1950s','1950s Rainy Street','Atmospheric street photograph','Leica IIIg','Black-and-white 35mm film','Wet pavement reflections, deep blacks, film scratches, moody grain'],
    [92,'1960s','1960s Newspaper Front Page','Press photograph','Speed Graphic','Black-and-white sheet film','Hard flash, high contrast, coarse print texture, editorial composition'],
    [93,'1970s','1970s Beach Polaroid','Beach snapshot','Polaroid SX-70','Instant film','Warm faded tones, soft focus, white border, slight color shift'],
    [94,'1980s','1980s Home Video Frame','Family home-video frame','VHS camcorder','VHS videotape','Analog noise, interlacing, timestamp, low-resolution colors'],
    [95,'1990s','1990s Flash Portrait','Casual portrait','Yashica T4','Color negative 35mm film','Hard frontal flash, red-eye, soft background, consumer-film grain'],
    [96,'2000s','2000s Flip-Phone Photo','Early mobile-phone snapshot','VGA camera phone','Low-resolution digital image','Pixelated detail, greenish tint, heavy compression, poor exposure'],
    [97,'2000s','2000s Blog Photo','Personal online photo','Compact digital camera','Compressed JPEG','Low resolution, flash glare, oversaturated colors, amateur framing'],
    [98,'2000s','2000s Documentary DSLR','Street documentary','Canon EOS 5D','Full-frame digital RAW','Natural light, subtle noise, realistic contrast, shallow depth of field'],
    [99,'2000s','2000s Concert Compact Camera','Concert snapshot','Casio Exilim compact camera','Small-sensor digital image','Digital noise, colored stage lights, motion blur, harsh flash'],
    [100,'2000s','2000s Scrapbook Photo','Printed personal snapshot','Fujifilm FinePix compact camera','Digital JPEG printed on consumer photo paper','Slightly faded print, glossy highlights, warm colors, casual composition'],
    [101,'2010s','2010s Instagram Street Photo','Urban lifestyle photograph','iPhone 4','Early smartphone digital image','Square crop, strong contrast, slight HDR effect, Instagram-style filter'],
    [102,'2010s','2010s Music Festival','Music festival photograph','Canon EOS 7D DSLR','Digital RAW image','Sharp details, colorful stage lights, shallow depth of field, natural skin tones'],
    [103,'2010s','2010s Smartphone Party','House party snapshot','iPhone 5','Smartphone JPEG','Phone flash, dark background, slight motion blur, cool shadows'],
    [104,'2010s','2010s Street Protest','Crowd documentary photograph','Canon EOS 5D Mark II','Full-frame digital RAW','Natural daylight, documentary framing, realistic colors, moderate contrast'],
    [105,'2010s','2010s Wedding Smartphone Photo','Wedding guest snapshot','Samsung Galaxy S4','Early smartphone JPEG','Slightly overprocessed colors, soft detail, indoor yellow lighting'],
    [106,'2010s','2010s Sports Stadium','Sports spectator photograph','Nikon D800 DSLR','High-resolution digital image','Crisp telephoto detail, vivid colors, sharp crowd background'],
    [107,'2010s','2010s Food Truck Festival','Street event photograph','Fujifilm X100','APS-C digital image','Warm colors, documentary composition, subtle film simulation, natural light'],
    [108,'2010s','2010s Graduation Selfie','Group selfie','iPhone 6','Smartphone digital image','Wide-angle distortion, bright daylight, high clarity, casual framing'],
    [109,'2010s','2010s Nightclub Photo','Nightlife snapshot','Compact digital camera with flash','Small-sensor digital JPEG','Harsh flash, colorful lights, red-eye, frozen foreground with dark background'],
    [110,'2010s','2010s Travel Blog Photo','Tourist photograph','Sony Alpha mirrorless camera','Digital RAW image','Bright natural colors, sharp landscape, light Instagram-style grading'],
    [111,'2020s','2020s Masked Street Photo','Urban documentary photograph','iPhone 12','Computational smartphone photography','Sharp HDR detail, balanced exposure, realistic street colors'],
    [112,'2020s','2020s Outdoor Concert','Live music photograph','Sony A7 III mirrorless camera','Full-frame digital RAW','Low-light clarity, colorful stage lights, smooth background blur'],
    [113,'2020s','2020s Protest Crowd','Public demonstration photograph','Canon EOS R6','Full-frame mirrorless digital image','Fast autofocus, natural daylight, sharp signs and faces, documentary realism'],
    [114,'2020s','2020s Backyard Wedding','Informal wedding photograph','Fujifilm X-T4','APS-C digital RAW','Soft natural light, muted tones, candid composition, shallow depth of field'],
    [115,'2020s','2020s Smartphone Selfie','Casual selfie','iPhone 13 Pro','Computational HDR image','Sharp facial detail, wide-angle perspective, natural skin smoothing'],
    [116,'2020s','2020s Street Festival','Public celebration photograph','Google Pixel 7','Computational smartphone image','Strong dynamic range, vivid colors, realistic shadows, candid framing'],
    [117,'2020s','2020s Sports Fan Photo','Sports crowd snapshot','Samsung Galaxy S22 Ultra','High-resolution smartphone JPEG','Sharp digital zoom, vivid colors, bright stadium lighting'],
    [118,'2020s','2020s Rooftop Party','Evening social photograph','Sony A7 IV','Full-frame digital RAW','Low-light detail, warm city lights, cinematic bokeh, natural expressions'],
    [119,'2020s','2020s Food Market Photo','Outdoor market photograph','Fujifilm X100V','Digital image with film simulation','Warm colors, subtle grain simulation, candid street composition'],
    [120,'2020s','2020s Documentary Portrait','Environmental portrait','Leica Q2','Full-frame digital RAW','High detail, natural light, restrained color grading, authentic expression'],
];

export const PHOTOGRAPHIC_PRESETS: PhotographicPreset[] = PRESETS.map(([id, era, name, photoType, cameraType, filmOrMedia, visualStyle]) => ({ id, era, name, photoType, cameraType, filmOrMedia, visualStyle }));
export const PHOTOGRAPHIC_ERAS = ['1950s', '1960s', '1970s', '1980s', '1990s', '2000s', '2010s', '2020s'];
