export interface HistoricalCameo {
    year: number;
    event: string;
    cameoIdea: string;
}

export const HISTORICAL_CAMEO_CATALOG: Record<string, HistoricalCameo[]> = {
    '1950s': [
        { year: 1950, event: 'The first Formula One World Championship race takes place at Silverstone', cameoIdea: 'A person posing beside vintage racing drivers and classic cars' },
        { year: 1951, event: 'The Festival of Britain opens in London', cameoIdea: 'A visitor posing among futuristic exhibits and cheerful crowds' },
        { year: 1952, event: 'The Helsinki Summer Olympics take place', cameoIdea: 'A person standing among athletes during an Olympic ceremony' },
        { year: 1953, event: 'Queen Elizabeth II is crowned at Westminster Abbey', cameoIdea: 'A guest in formal clothing standing among the royal crowd' },
        { year: 1954, event: 'The FIFA World Cup takes place in Switzerland', cameoIdea: 'A spectator celebrating in a packed football stadium' },
        { year: 1955, event: 'Disneyland opens in Anaheim, California', cameoIdea: 'A visitor posing near the entrance with early Disneyland guests' },
        { year: 1956, event: 'Elvis Presley performs on The Ed Sullivan Show', cameoIdea: "A person dancing near the studio audience during Elvis's performance" },
        { year: 1957, event: 'The Little Rock Nine attend Central High School', cameoIdea: 'A respectful newspaper-style street scene outside the school' },
        { year: 1958, event: 'The Hula Hoop craze spreads across America', cameoIdea: 'A person attempting to hula hoop in a busy suburban street' },
        { year: 1959, event: 'The first Grammy Awards ceremony takes place', cameoIdea: 'A person posing beside glamorous musicians at an awards event' },
    ],
    '1960s': [
        { year: 1960, event: 'The Rome Summer Olympics take place', cameoIdea: 'A spectator watching runners in a crowded stadium' },
        { year: 1961, event: 'John F. Kennedy is inaugurated as President of the United States', cameoIdea: 'A person standing among the crowd at the Capitol ceremony' },
        { year: 1962, event: 'The Beatles begin performing at the Cavern Club in Liverpool', cameoIdea: 'A fan standing inside the packed club near the stage' },
        { year: 1963, event: "Martin Luther King Jr. delivers the 'I Have a Dream' speech", cameoIdea: 'A person standing peacefully among the large crowd in Washington' },
        { year: 1964, event: 'The Beatles perform on The Ed Sullivan Show', cameoIdea: 'A screaming fan in the television studio audience' },
        { year: 1965, event: 'The first Monterey Pop Festival takes place', cameoIdea: 'A festival attendee wearing colorful clothes in a relaxed crowd' },
        { year: 1966, event: 'England wins the FIFA World Cup', cameoIdea: 'A supporter celebrating with fans outside Wembley Stadium' },
        { year: 1967, event: 'The Summer of Love takes place in San Francisco', cameoIdea: 'A flower-power visitor in a colorful Haight-Ashbury street scene' },
        { year: 1968, event: 'The Mexico City Summer Olympics take place', cameoIdea: 'A spectator watching athletes during the opening ceremony' },
        { year: 1969, event: 'The Woodstock Music and Art Fair takes place', cameoIdea: 'A muddy festival attendee sitting among the Woodstock crowd' },
    ],
    '1970s': [
        { year: 1970, event: 'Brazil wins the FIFA World Cup in Mexico', cameoIdea: 'A fan celebrating with Brazilian supporters in the stadium' },
        { year: 1971, event: 'The Concert for Bangladesh takes place at Madison Square Garden', cameoIdea: 'A concertgoer standing among the audience with a donation sign' },
        { year: 1972, event: 'The Munich Summer Olympics take place', cameoIdea: 'A tourist posing with athletes in the Olympic village' },
        { year: 1973, event: 'The Battle of the Sexes tennis match takes place', cameoIdea: 'A spectator reacting dramatically from the tennis stands' },
        { year: 1974, event: 'The Rumble in the Jungle boxing match takes place', cameoIdea: 'A spectator holding a handmade boxing sign in the crowd' },
        { year: 1975, event: 'The first Saturday Night Live episode airs', cameoIdea: 'A person waiting outside the television studio with comedy fans' },
        { year: 1976, event: 'The Montreal Summer Olympics take place', cameoIdea: 'A visitor posing with athletes near the Olympic stadium' },
        { year: 1977, event: "The Queen's Silver Jubilee celebrations take place", cameoIdea: 'A person waving a small flag during a street celebration' },
        { year: 1978, event: 'The Bee Gees perform during the disco era', cameoIdea: 'A person dancing beside a crowded disco dance floor' },
        { year: 1979, event: 'The first Notting Hill Carnival takes place', cameoIdea: 'A colorful parade participant surrounded by dancers and musicians' },
    ],
    '1980s': [
        { year: 1980, event: 'The Miracle on Ice takes place at the Winter Olympics', cameoIdea: 'An excited spectator celebrating with American hockey fans' },
        { year: 1981, event: 'The wedding of Prince Charles and Lady Diana takes place', cameoIdea: 'A spectator standing behind barriers in a festive London crowd' },
        { year: 1982, event: 'Italy wins the FIFA World Cup', cameoIdea: 'A football fan celebrating in the streets of Madrid' },
        { year: 1983, event: 'The first New York City Marathon becomes a major international event', cameoIdea: 'A runner or spectator posing on the crowded marathon route' },
        { year: 1984, event: 'The Los Angeles Summer Olympics take place', cameoIdea: 'A spectator wearing colorful Olympic clothing in the stadium' },
        { year: 1985, event: 'Live Aid concerts take place in London and Philadelphia', cameoIdea: 'A concertgoer holding a homemade Live Aid sign' },
        { year: 1986, event: 'Argentina wins the FIFA World Cup', cameoIdea: 'A fan celebrating with a blue-and-white crowd' },
        { year: 1987, event: 'The first Rugby World Cup takes place', cameoIdea: 'A supporter posing in a packed rugby stadium' },
        { year: 1988, event: 'The Seoul Summer Olympics take place', cameoIdea: 'A visitor standing among international spectators' },
        { year: 1989, event: 'The Berlin Wall falls', cameoIdea: 'A person celebrating on top of the wall with cheering crowds' },
    ],
    '1990s': [
        { year: 1990, event: 'The FIFA World Cup takes place in Italy', cameoIdea: 'A fan posing with football supporters outside the stadium' },
        { year: 1991, event: 'The Freddie Mercury Tribute Concert takes place at Wembley Stadium', cameoIdea: 'A concert fan holding a lighter among the audience' },
        { year: 1992, event: 'The Barcelona Summer Olympics take place', cameoIdea: 'A tourist posing with athletes near the Olympic village' },
        { year: 1993, event: 'The first MTV Unplugged performances become a major cultural event', cameoIdea: 'A person sitting among an intimate studio audience' },
        { year: 1994, event: 'Brazil wins the FIFA World Cup in the United States', cameoIdea: 'A supporter celebrating with Brazilian fans in the stands' },
        { year: 1995, event: 'The Rugby World Cup final takes place in South Africa', cameoIdea: 'A spectator wearing a colorful rugby jersey' },
        { year: 1996, event: 'The Atlanta Summer Olympics take place', cameoIdea: 'A visitor posing with Olympic spectators and volunteers' },
        { year: 1997, event: 'The Notting Hill Carnival becomes a major London street celebration', cameoIdea: 'A person dancing beside colorful floats and parade participants' },
        { year: 1998, event: 'France wins the FIFA World Cup', cameoIdea: 'A fan celebrating on the Champs-Elysees with a huge crowd' },
        { year: 1999, event: "The Woodstock '99 music festival takes place", cameoIdea: 'A festival attendee posing in a crowded concert field' },
    ],
    '2000s': [
        { year: 2000, event: 'The Sydney Summer Olympics take place', cameoIdea: 'A visitor posing with athletes during the opening celebrations' },
        { year: 2001, event: 'The first Big Day Out music festival of the new millennium takes place', cameoIdea: 'A concertgoer wearing early-2000s clothing in a festival crowd' },
        { year: 2002, event: 'Brazil wins the FIFA World Cup in Japan and South Korea', cameoIdea: 'A fan celebrating with Brazilian supporters after the final' },
        { year: 2003, event: 'The Rugby World Cup final takes place in Sydney', cameoIdea: 'A supporter posing with fans outside the stadium' },
        { year: 2004, event: 'The Athens Summer Olympics take place', cameoIdea: 'A tourist posing near ancient Greek landmarks with Olympic spectators' },
        { year: 2005, event: 'The Live 8 concerts take place around the world', cameoIdea: 'A concert attendee holding a colorful event sign' },
        { year: 2006, event: 'Italy wins the FIFA World Cup in Germany', cameoIdea: 'A supporter celebrating with Italian fans in Berlin' },
        { year: 2007, event: 'The Glastonbury Festival becomes a major international music event', cameoIdea: 'A muddy festivalgoer wearing rain boots and a colorful raincoat' },
        { year: 2008, event: "The Beijing Summer Olympics take place", cameoIdea: "A visitor posing with athletes near the Bird's Nest stadium" },
        { year: 2009, event: "Barack Obama's inauguration takes place in Washington, D.C.", cameoIdea: 'A bundled-up spectator standing among the enormous crowd' },
    ],
};
